<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="/style/actionButton.css">
    <title>SHOP</title>
</head>
<body>
<h2 style="margin-left: 10px">Подробная информация</h2>
<hr>
<b style="margin-left: 10px">Название: </b>${accessor.nameOfAccessor}<br>
<b style="margin-left: 10px">Производитель: </b>${accessor.manufacturerOfAccessor}<br>
<b style="margin-left: 10px">Стоимость: </b>${accessor.priceOfAccessor} BYN<br>
<b style="margin-left: 10px">Количество: </b>${accessor.amount_of_accessories}<br>
<b style="margin-left: 10px">Животное: </b>${accessor.animal.kindOfAnimal}<br>
