<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="/style/actionButton.css">
    <title>SHOP</title>
</head>
<body>
<h2 style="margin-left: 10px">Подробная информация</h2><hr>
<b style="margin-left: 10px">Название: </b>${feeds.nameOfFeed}<br>
<b style="margin-left: 10px">Производитель: </b>${feeds.manufacturerOfFeed}<br>
<b style="margin-left: 10px">Вес: </b>${feeds.weightOfFeed} кг<br>
<b style="margin-left: 10px">Стоимость: </b>${feeds.priceOfFeed} BYN<br>
<b style="margin-left: 10px">Количество: </b>${feeds.amountOfFeeds}<br>
<b style="margin-left: 10px">Животное: </b>${feeds.animal.kindOfAnimal}
</body>
</html>