<!DOCTYPE html>
<html>
<head>
    <title>SHOP</title>
</head>
<body>
<h2>Подробная информация</h2><hr>
<b>Название:</b>${feeds.nameOfFeed}<br>
<b>Производитель :</b>${feeds.manufacturer_of_feed}<br>
<b>Вес:</b>${feeds.weight_of_feed}<br>
<b>Стоимость:</b>${feeds.price_of_feed}<br>
<b>Количество:</b>${feeds.amount_of_feeds}<br>
<b>Животное:</b>${feeds.animal_id_for_feed.kindOfAnimal}
</body>
</html>